builds:
  - binary: envkey-fetch
    ldflags: '-extldflags "-static"'
    env:
      - CGO_ENABLED=0
      - GOROOT_FINAL=/usr/go
    goos:
      - darwin
      - linux
      - windows
      - freebsd

